
export type CurrencyCodeType = { currency: string, country: string, currency_name: string, symbol: string, }

export const CurrencyCode: CurrencyCodeType[] = [
    {
        'currency': 'AFN',
        'country': 'Afghanistan',
        'currency_name': 'Afghan Afghani',
        'symbol': '&#1547;',
    },
    {
        'currency': 'EUR',
        'country': 'France',
        'currency_name': 'Euro',
        'symbol': '&#8364;',
    },
    {
        'currency': 'ALL',
        'country': 'Albania',
        'currency_name': 'Albanian Lek',
        'symbol': '&#76;&#101;&#107;',
    },
    {
        'currency': 'DZD',
        'country': 'Algeria',
        'currency_name': 'Algerian Dinar',
        'symbol': '',
    },
    {
        'currency': 'USD',
        'country': 'United States of America',
        'currency_name': 'US Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'AOA',
        'country': 'Angola',
        'currency_name': 'Angolan Kwanza',
        'symbol': '',
    },
    {
        'currency': 'XCD',
        'country': 'Antigua and Barbuda',
        'currency_name': 'East Caribbean Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'ARS',
        'country': 'Argentina',
        'currency_name': 'Argentine Peso',
        'symbol': '&#36;',
    },
    {
        'currency': 'AMD',
        'country': 'Armenia',
        'currency_name': 'Armenian Dram',
        'symbol': '',
    },
    {
        'currency': 'AWG',
        'country': 'Aruba',
        'currency_name': 'Aruban Florin',
        'symbol': '&#402;',
    },
    {
        'currency': 'AUD',
        'country': 'Australia',
        'currency_name': 'Australian Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'AZN',
        'country': 'Azerbaijan',
        'currency_name': 'Azerbaijani Manat',
        'symbol': '&#1084;&#1072;&#1085;',
    },
    {
        'currency': 'BSD',
        'country': 'Bahamas',
        'currency_name': 'Bahamian Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'BHD',
        'country': 'Bahrain',
        'currency_name': 'Bahraini Dinar',
        'symbol': '',
    },
    {
        'currency': 'BDT',
        'country': 'Bangladesh',
        'currency_name': 'Bangladeshi Taka',
        'symbol': '',
    },
    {
        'currency': 'BBD',
        'country': 'Barbados',
        'currency_name': 'Barbadian Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'BYN',
        'country': 'Belarus',
        'currency_name': 'Belarusian Ruble',
        'symbol': '',
    },
    {
        'currency': 'BZD',
        'country': 'Belize',
        'currency_name': 'Belize Dollar',
        'symbol': '&#66;&#90;&#36;',
    },
    {
        'currency': 'XOF',
        'country': 'Benin',
        'currency_name': 'West African CFA Franc',
        'symbol': '',
    },
    {
        'currency': 'BMD',
        'country': 'Bermuda',
        'currency_name': 'Bermudian Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'BTN',
        'country': 'Bhutan',
        'currency_name': 'Bhutanese Ngultrum',
        'symbol': '',
    },
    {
        'currency': 'BOB',
        'country': 'Bolivia',
        'currency_name': 'Bolivian Boliviano',
        'symbol': '&#36;&#98;',
    },
    {
        'currency': 'BAM',
        'country': 'Bosnia and Herzegovina',
        'currency_name': 'Bosnia and Herzegovina Convertible Mark',
        'symbol': '&#75;&#77;',
    },
    {
        'currency': 'BWP',
        'country': 'Botswana',
        'currency_name': 'Botswana Pula',
        'symbol': '&#80;',
    },
    {
        'currency': 'BRL',
        'country': 'Brazil',
        'currency_name': 'Brazilian Real',
        'symbol': '&#82;&#36;',
    },
    {
        'currency': 'BND',
        'country': 'Brunei',
        'currency_name': 'Brunei Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'BGN',
        'country': 'Bulgaria',
        'currency_name': 'Bulgarian Lev',
        'symbol': '&#1083;&#1074;',
    },
    {
        'currency': 'BIF',
        'country': 'Burundi',
        'currency_name': 'Burundian Franc',
        'symbol': '',
    },
    {
        'currency': 'CVE',
        'country': 'Cabo Verde',
        'currency_name': 'Cape Verdean Escudo',
        'symbol': '',
    },
    {
        'currency': 'KHR',
        'country': 'Cambodia',
        'currency_name': 'Cambodian Riel',
        'symbol': '&#6107;',
    },
    {
        'currency': 'XAF',
        'country': 'Cameroon',
        'currency_name': 'Central African CFA Franc',
        'symbol': '',
    },
    {
        'currency': 'CAD',
        'country': 'Canada',
        'currency_name': 'Canadian Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'KYD',
        'country': 'Cayman Islands',
        'currency_name': 'Cayman Islands Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'CLP',
        'country': 'Chile',
        'currency_name': 'Chilean Peso',
        'symbol': '&#36;',
    },
    {
        'currency': 'CNY',
        'country': 'China',
        'currency_name': 'Chinese Yuan',
        'symbol': '&#165;',
    },
    {
        'currency': 'COP',
        'country': 'Colombia',
        'currency_name': 'Colombian Peso',
        'symbol': '&#36;',
    },
    {
        'currency': 'KMF',
        'country': 'Comoros',
        'currency_name': 'Comorian Franc',
        'symbol': '',
    },
    {
        'currency': 'CDF',
        'country': 'Congo (Democratic Republic)',
        'currency_name': 'Congolese Franc',
        'symbol': '',
    },
    {
        'currency': 'CRC',
        'country': 'Costa Rica',
        'currency_name': 'Costa Rican Colón',
        'symbol': '&#8353;',
    },
    {
        'currency': 'CUP',
        'country': 'Cuba',
        'currency_name': 'Cuban Peso',
        'symbol': '&#8369;',
    },
    {
        'currency': 'ANG',
        'country': 'Curaçao',
        'currency_name': 'Netherlands Antillean Guilder',
        'symbol': '&#402;',
    },
    {
        'currency': 'CZK',
        'country': 'Czech Republic',
        'currency_name': 'Czech Koruna',
        'symbol': '&#75;&#269;',
    },
    {
        'currency': 'DKK',
        'country': 'Denmark',
        'currency_name': 'Danish Krone',
        'symbol': '&#107;&#114;',
    },
    {
        'currency': 'DJF',
        'country': 'Djibouti',
        'currency_name': 'Djiboutian Franc',
        'symbol': '',
    },
    {
        'currency': 'DOP',
        'country': 'Dominican Republic',
        'currency_name': 'Dominican Peso',
        'symbol': '&#82;&#68;&#36;',
    },
    {
        'currency': 'EGP',
        'country': 'Egypt',
        'currency_name': 'Egyptian Pound',
        'symbol': '&#163;',
    },
    {
        'currency': 'ERN',
        'country': 'Eritrea',
        'currency_name': 'Eritrean Nakfa',
        'symbol': '',
    },
    {
        'currency': 'ETB',
        'country': 'Ethiopia',
        'currency_name': 'Ethiopian Birr',
        'symbol': '',
    },
    {
        'currency': 'FJD',
        'country': 'Fiji',
        'currency_name': 'Fijian Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'GMD',
        'country': 'Gambia',
        'currency_name': 'Gambian Dalasi',
        'symbol': '',
    },
    {
        'currency': 'GEL',
        'country': 'Georgia',
        'currency_name': 'Georgian Lari',
        'symbol': '',
    },
    {
        'currency': 'GHS',
        'country': 'Ghana',
        'currency_name': 'Ghanaian Cedi',
        'symbol': '',
    },
    {
        'currency': 'GIP',
        'country': 'Gibraltar',
        'currency_name': 'Gibraltar Pound',
        'symbol': '&#163;',
    },
    {
        'currency': 'GTQ',
        'country': 'Guatemala',
        'currency_name': 'Guatemalan Quetzal',
        'symbol': '&#81;',
    },
    {
        'currency': 'GNF',
        'country': 'Guinea',
        'currency_name': 'Guinean Franc',
        'symbol': '',
    },
    {
        'currency': 'GYD',
        'country': 'Guyana',
        'currency_name': 'Guyanese Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'HTG',
        'country': 'Haiti',
        'currency_name': 'Haitian Gourde',
        'symbol': '',
    },
    {
        'currency': 'HNL',
        'country': 'Honduras',
        'currency_name': 'Honduran Lempira',
        'symbol': '&#76;',
    },
    {
        'currency': 'HKD',
        'country': 'Hong Kong',
        'currency_name': 'Hong Kong Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'HUF',
        'country': 'Hungary',
        'currency_name': 'Hungarian Forint',
        'symbol': '&#70;&#116;',
    },
    {
        'currency': 'ISK',
        'country': 'Iceland',
        'currency_name': 'Icelandic Króna',
        'symbol': '&#107;&#114;',
    },
    {
        'currency': 'INR',
        'country': 'India',
        'currency_name': 'Indian Rupee',
        'symbol': '&#8377;',
    },
    {
        'currency': 'IDR',
        'country': 'Indonesia',
        'currency_name': 'Indonesian Rupiah',
        'symbol': '&#82;&#112;',
    },
    {
        'currency': 'IRR',
        'country': 'Iran',
        'currency_name': 'Iranian Rial',
        'symbol': '&#65020;',
    },
    {
        'currency': 'IQD',
        'country': 'Iraq',
        'currency_name': 'Iraqi Dinar',
        'symbol': '',
    },
    {
        'currency': 'ILS',
        'country': 'Israel',
        'currency_name': 'Israeli New Shekel',
        'symbol': '&#8362;',
    },
    {
        'currency': 'JMD',
        'country': 'Jamaica',
        'currency_name': 'Jamaican Dollar',
        'symbol': '&#74;&#36;',
    },
    {
        'currency': 'JPY',
        'country': 'Japan',
        'currency_name': 'Japanese Yen',
        'symbol': '&#165;',
    },
    {
        'currency': 'JOD',
        'country': 'Jordan',
        'currency_name': 'Jordanian Dinar',
        'symbol': '',
    },
    {
        'currency': 'KZT',
        'country': 'Kazakhstan',
        'currency_name': 'Kazakhstani Tenge',
        'symbol': '&#1083;&#1074;',
    },
    {
        'currency': 'KES',
        'country': 'Kenya',
        'currency_name': 'Kenyan Shilling',
        'symbol': '',
    },
    {
        'currency': 'KWD',
        'country': 'Kuwait',
        'currency_name': 'Kuwaiti Dinar',
        'symbol': '',
    },
    {
        'currency': 'KGS',
        'country': 'Kyrgyzstan',
        'currency_name': 'Kyrgyzstani Som',
        'symbol': '&#1083;&#1074;',
    },
    {
        'currency': 'LAK',
        'country': 'Laos',
        'currency_name': 'Lao Kip',
        'symbol': '&#8365;',
    },
    {
        'currency': 'LBP',
        'country': 'Lebanon',
        'currency_name': 'Lebanese Pound',
        'symbol': '&#163;',
    },
    {
        'currency': 'LSL',
        'country': 'Lesotho',
        'currency_name': 'Lesotho Loti',
        'symbol': '',
    },
    {
        'currency': 'LRD',
        'country': 'Liberia',
        'currency_name': 'Liberian Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'LYD',
        'country': 'Libya',
        'currency_name': 'Libyan Dinar',
        'symbol': '',
    },
    {
        'currency': 'CHF',
        'country': 'Switzerland',
        'currency_name': 'Swiss Franc',
        'symbol': '&#67;&#72;&#70;',
    },
    {
        'currency': 'MOP',
        'country': 'Macao',
        'currency_name': 'Macanese Pataca',
        'symbol': '',
    },
    {
        'currency': 'MGA',
        'country': 'Madagascar',
        'currency_name': 'Malagasy Ariary',
        'symbol': '',
    },
    {
        'currency': 'MWK',
        'country': 'Malawi',
        'currency_name': 'Malawian Kwacha',
        'symbol': '',
    },
    {
        'currency': 'MYR',
        'country': 'Malaysia',
        'currency_name': 'Malaysian Ringgit',
        'symbol': '&#82;&#77;',
    },
    {
        'currency': 'MVR',
        'country': 'Maldives',
        'currency_name': 'Maldivian Rufiyaa',
        'symbol': '',
    },
    {
        'currency': 'MRU',
        'country': 'Mauritania',
        'currency_name': 'Mauritanian Ouguiya',
        'symbol': '',
    },
    {
        'currency': 'MUR',
        'country': 'Mauritius',
        'currency_name': 'Mauritian Rupee',
        'symbol': '&#8360;',
    },
    {
        'currency': 'MXN',
        'country': 'Mexico',
        'currency_name': 'Mexican Peso',
        'symbol': '&#36;',
    },
    {
        'currency': 'MDL',
        'country': 'Moldova',
        'currency_name': 'Moldovan Leu',
        'symbol': '',
    },
    {
        'currency': 'MNT',
        'country': 'Mongolia',
        'currency_name': 'Mongolian Tögrög',
        'symbol': '&#8366;',
    },
    {
        'currency': 'MAD',
        'country': 'Morocco',
        'currency_name': 'Moroccan Dirham',
        'symbol': '',
    },
    {
        'currency': 'MZN',
        'country': 'Mozambique',
        'currency_name': 'Mozambican Metical',
        'symbol': '&#77;&#84;',
    },
    {
        'currency': 'MMK',
        'country': 'Myanmar',
        'currency_name': 'Burmese Kyat',
        'symbol': '',
    },
    {
        'currency': 'NAD',
        'country': 'Namibia',
        'currency_name': 'Namibian Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'NPR',
        'country': 'Nepal',
        'currency_name': 'Nepalese Rupee',
        'symbol': '&#8360;',
    },
    {
        'currency': 'NZD',
        'country': 'New Zealand',
        'currency_name': 'New Zealand Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'NIO',
        'country': 'Nicaragua',
        'currency_name': 'Nicaraguan Córdoba',
        'symbol': '&#67;&#36;',
    },
    {
        'currency': 'NGN',
        'country': 'Nigeria',
        'currency_name': 'Nigerian Naira',
        'symbol': '&#8358;',
    },
    {
        'currency': 'KPW',
        'country': 'North Korea',
        'currency_name': 'North Korean Won',
        'symbol': '&#8361;',
    },
    {
        'currency': 'MKD',
        'country': 'North Macedonia',
        'currency_name': 'Macedonian Denar',
        'symbol': '&#1076;&#1077;&#1085;',
    },
    {
        'currency': 'NOK',
        'country': 'Norway',
        'currency_name': 'Norwegian Krone',
        'symbol': '&#107;&#114;',
    },
    {
        'currency': 'OMR',
        'country': 'Oman',
        'currency_name': 'Omani Rial',
        'symbol': '&#65020;',
    },
    {
        'currency': 'PKR',
        'country': 'Pakistan',
        'currency_name': 'Pakistani Rupee',
        'symbol': '&#8360;',
    },
    {
        'currency': 'PAB',
        'country': 'Panama',
        'currency_name': 'Panamanian Balboa',
        'symbol': '&#66;&#47;&#46;',
    },
    {
        'currency': 'PGK',
        'country': 'Papua New Guinea',
        'currency_name': 'Papua New Guinean Kina',
        'symbol': '',
    },
    {
        'currency': 'PYG',
        'country': 'Paraguay',
        'currency_name': 'Paraguayan Guaraní',
        'symbol': '&#71;&#115;',
    },
    {
        'currency': 'PEN',
        'country': 'Peru',
        'currency_name': 'Peruvian Sol',
        'symbol': '&#83;&#47;&#46;',
    },
    {
        'currency': 'PHP',
        'country': 'Philippines',
        'currency_name': 'Philippine Peso',
        'symbol': '&#8369;',
    },
    {
        'currency': 'PLN',
        'country': 'Poland',
        'currency_name': 'Polish Złoty',
        'symbol': '&#122;&#322;',
    },
    {
        'currency': 'QAR',
        'country': 'Qatar',
        'currency_name': 'Qatari Riyal',
        'symbol': '&#65020;',
    },
    {
        'currency': 'RON',
        'country': 'Romania',
        'currency_name': 'Romanian Leu',
        'symbol': '&#108;&#101;&#105;',
    },
    {
        'currency': 'RUB',
        'country': 'Russia',
        'currency_name': 'Russian Ruble',
        'symbol': '&#1088;&#1091;&#1073;',
    },
    {
        'currency': 'RWF',
        'country': 'Rwanda',
        'currency_name': 'Rwandan Franc',
        'symbol': '',
    },
    {
        'currency': 'WST',
        'country': 'Samoa',
        'currency_name': 'Samoan Tālā',
        'symbol': '',
    },
    {
        'currency': 'STN',
        'country': 'São Tomé and Príncipe',
        'currency_name': 'São Tomé and Príncipe Dobra',
        'symbol': '',
    },
    {
        'currency': 'SAR',
        'country': 'Saudi Arabia',
        'currency_name': 'Saudi Riyal',
        'symbol': '&#65020;',
    },
    {
        'currency': 'RSD',
        'country': 'Serbia',
        'currency_name': 'Serbian Dinar',
        'symbol': '&#1044;&#1080;&#1085;&#46;',
    },
    {
        'currency': 'SCR',
        'country': 'Seychelles',
        'currency_name': 'Seychellois Rupee',
        'symbol': '&#8360;',
    },
    {
        'currency': 'SLL',
        'country': 'Sierra Leone',
        'currency_name': 'Sierra Leonean Leone',
        'symbol': '',
    },
    {
        'currency': 'SGD',
        'country': 'Singapore',
        'currency_name': 'Singapore Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'SBD',
        'country': 'Solomon Islands',
        'currency_name': 'Solomon Islands Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'SOS',
        'country': 'Somalia',
        'currency_name': 'Somali Shilling',
        'symbol': '&#83;',
    },
    {
        'currency': 'ZAR',
        'country': 'South Africa',
        'currency_name': 'South African Rand',
        'symbol': '&#82;',
    },
    {
        'currency': 'KRW',
        'country': 'South Korea',
        'currency_name': 'South Korean Won',
        'symbol': '&#8361;',
    },
    {
        'currency': 'SSP',
        'country': 'South Sudan',
        'currency_name': 'South Sudanese Pound',
        'symbol': '',
    },
    {
        'currency': 'LKR',
        'country': 'Sri Lanka',
        'currency_name': 'Sri Lankan Rupee',
        'symbol': '&#8360;',
    },
    {
        'currency': 'SDG',
        'country': 'Sudan',
        'currency_name': 'Sudanese Pound',
        'symbol': '',
    },
    {
        'currency': 'SRD',
        'country': 'Suriname',
        'currency_name': 'Surinamese Dollar',
        'symbol': '&#36;',
    },
    {
        'currency': 'SEK',
        'country': 'Sweden',
        'currency_name': 'Swedish Krona',
        'symbol': '&#107;&#114;',
    },
    {
        'currency': 'SYP',
        'country': 'Syria',
        'currency_name': 'Syrian Pound',
        'symbol': '&#163;',
    },
    {
        'currency': 'TWD',
        'country': 'Taiwan',
        'currency_name': 'New Taiwan Dollar',
        'symbol': '&#78;&#84;&#36;',
    },
    {
        'currency': 'TJS',
        'country': 'Tajikistan',
        'currency_name': 'Tajikistani Somoni',
        'symbol': '',
    },
    {
        'currency': 'TZS',
        'country': 'Tanzania',
        'currency_name': 'Tanzanian Shilling',
        'symbol': '',
    },
    {
        'currency': 'THB',
        'country': 'Thailand',
        'currency_name': 'Thai Baht',
        'symbol': '&#3647;',
    },
    {
        'currency': 'TND',
        'country': 'Tunisia',
        'currency_name': 'Tunisian Dinar',
        'symbol': '',
    },
    {
        'currency': 'TRY',
        'country': 'Turkey',
        'currency_name': 'Turkish Lira',
        'symbol': '',
    },
    {
        'currency': 'TMT',
        'country': 'Turkmenistan',
        'currency_name': 'Turkmenistan Manat',
        'symbol': '',
    },
    {
        'currency': 'UGX',
        'country': 'Uganda',
        'currency_name': 'Ugandan Shilling',
        'symbol': '',
    },
    {
        'currency': 'UAH',
        'country': 'Ukraine',
        'currency_name': 'Ukrainian Hryvnia',
        'symbol': '&#8372;',
    },
    {
        'currency': 'AED',
        'country': 'United Arab Emirates',
        'currency_name': 'UAE Dirham',
        'symbol': '',
    },
    {
        'currency': 'GBP',
        'country': 'United Kingdom',
        'currency_name': 'Pound Sterling',
        'symbol': '&#163;',
    },
    {
        'currency': 'UYU',
        'country': 'Uruguay',
        'currency_name': 'Uruguayan Peso',
        'symbol': '&#36;&#85;',
    },
    {
        'currency': 'UZS',
        'country': 'Uzbekistan',
        'currency_name': 'Uzbekistani Soʻm',
        'symbol': '&#1083;&#1074;',
    },
    {
        'currency': 'VUV',
        'country': 'Vanuatu',
        'currency_name': 'Vanuatu Vatu',
        'symbol': '',
    },
    {
        'currency': 'VES',
        'country': 'Venezuela',
        'currency_name': 'Venezuelan Bolívar',
        'symbol': '',
    },
    {
        'currency': 'VND',
        'country': 'Vietnam',
        'currency_name': 'Vietnamese Đồng',
        'symbol': '&#8363;',
    },
    {
        'currency': 'YER',
        'country': 'Yemen',
        'currency_name': 'Yemeni Rial',
        'symbol': '&#65020;',
    },
    {
        'currency': 'ZMW',
        'country': 'Zambia',
        'currency_name': 'Zambian Kwacha',
        'symbol': '',
    },
    {
        'currency': 'ZWL',
        'country': 'Zimbabwe',
        'currency_name': 'Zimbabwean Dollar',
        'symbol': '',
    },
];
