import { AccountingGroups } from './types';

export const accountGroups: AccountingGroups[] = [{
    '_id': '1b742e39-ccd3-46be-b11a-501130cd82f7',
    'accounting_group_name': 'Capital Account',
    'user_id': null,
    'company_id': null,
    'description': "Owner's capital and retained earnings",
    'image': null,
    'is_deleted': false,
    'parent': 'Primary Group',
},
{
    '_id': 'ad7bef31-fb19-41b8-9ad0-825936806bf8',
    'accounting_group_name': 'Loans (Liability)',
    'user_id': null,
    'company_id': null,
    'description': 'All loan liabilities',
    'image': null,
    'is_deleted': false,
    'parent': 'Capital Account',
},
{
    '_id': '8d96d7b3-12fc-49f5-8bbb-c416c64f3567',
    'accounting_group_name': 'Sales Account',
    'user_id': null,
    'company_id': null,
    'description': 'Sales income group',
    'image': null,
    'is_deleted': false,
    'parent': 'Primary Group',
},
{
    '_id': 'e73a4f44-f3af-4851-b36e-103da84580c1',
    'accounting_group_name': 'Purchase Account',
    'user_id': null,
    'company_id': null,
    'description': 'Purchases made by company',
    'image': null,
    'is_deleted': false,
    'parent': 'Primary Group',
},
{
    '_id': '8d4ed7ad-c461-414d-ab3b-95b9d0b9ff91',
    'accounting_group_name': 'Indirect Expenses',
    'user_id': null,
    'company_id': null,
    'description': 'Expenses not directly related to production',
    'image': null,
    'is_deleted': false,
    'parent': 'Primary Group',
},
{
    '_id': 'ad0b6203-916a-4bf3-aa69-b660874da374',
    'accounting_group_name': 'Indirect Incomes',
    'user_id': null,
    'company_id': null,
    'description': 'Incomes not from core operations',
    'image': null,
    'is_deleted': false,
    'parent': 'Primary Group',
},
{
    '_id': '4fb782c6-dd52-4d7a-aed3-f70fed36686c',
    'accounting_group_name': 'Current Assets',
    'user_id': null,
    'company_id': null,
    'description': 'Assets that can be converted to cash',
    'image': null,
    'is_deleted': false,
    'parent': 'Primary Group',
},
{
    '_id': '3295a3bc-e4ff-4567-8922-233f07cc739f',
    'accounting_group_name': 'Current Liabilities',
    'user_id': null,
    'company_id': null,
    'description': 'Liabilities due within one year',
    'image': null,
    'is_deleted': false,
    'parent': 'Primary Group',
},
{
    '_id': 'caea08ac-37fe-4f3b-9577-a6ed78777fa3',
    'accounting_group_name': 'Bank Accounts',
    'user_id': null,
    'company_id': null,
    'description': 'Bank balances and transactions',
    'image': null,
    'is_deleted': false,
    'parent': 'Current Assets',
},
{
    '_id': '173bb3e5-2376-4a7b-a9cf-27cb6b14180e',
    'accounting_group_name': 'Sundry Debtors',
    'user_id': null,
    'company_id': null,
    'description': 'Customers to whom amounts are receivable',
    'image': null,
    'is_deleted': false,
    'parent': 'Current Assets',
},
{
    '_id': '375ccd79-bbf4-469e-8ece-8a1210c85f38',
    'accounting_group_name': 'Sundry Creditors',
    'user_id': null,
    'company_id': null,
    'description': 'Suppliers from whom amounts are payable',
    'image': null,
    'is_deleted': false,
    'parent': 'Current Liabilities',
},
{
    '_id': '342e7376-e1f2-4380-bc21-c7bd2d7722af',
    'accounting_group_name': 'Duties & Taxes',
    'user_id': null,
    'company_id': null,
    'description': 'Indirect taxes like GST, VAT, etc.',
    'image': null,
    'is_deleted': false,
    'parent': 'Current Liabilities',
},
{
    '_id': '1c10b9db-632d-4b08-b477-b39489aa6fe7',
    'accounting_group_name': 'Stock-in-Hand',
    'user_id': null,
    'company_id': null,
    'description': 'Closing stock of inventory items',
    'image': null,
    'is_deleted': false,
    'parent': 'Current Assets',
},
{
    '_id': '4cada6b7-86e5-4c3e-ae7f-9edee0be4aff',
    'accounting_group_name': 'Fixed Assets',
    'user_id': null,
    'company_id': null,
    'description': 'Long-term tangible assets',
    'image': null,
    'is_deleted': false,
    'parent': 'Primary Group',
}];
